// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPAqUP29ZGiugJMSqUkOADgtBkTfmc-W4',
    appId: '1:451148309163:web:e02fa496ee9db925e4cdee',
    messagingSenderId: '451148309163',
    projectId: 'taxiappdemo-1abe7',
    authDomain: 'taxiappdemo-1abe7.firebaseapp.com',
    storageBucket: 'taxiappdemo-1abe7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrFk1ZrqRh93wi6qxu33er2U6pEx-vDB4',
    appId: '1:451148309163:android:158cd2f2b6abdd28e4cdee',
    messagingSenderId: '451148309163',
    projectId: 'taxiappdemo-1abe7',
    storageBucket: 'taxiappdemo-1abe7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5xwuFJuGUKj7wa4LmvCZCYcKt84qw75c',
    appId: '1:451148309163:ios:ae9713a9ad817a25e4cdee',
    messagingSenderId: '451148309163',
    projectId: 'taxiappdemo-1abe7',
    storageBucket: 'taxiappdemo-1abe7.firebasestorage.app',
    iosBundleId: 'com.example.taxiappdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5xwuFJuGUKj7wa4LmvCZCYcKt84qw75c',
    appId: '1:451148309163:ios:ae9713a9ad817a25e4cdee',
    messagingSenderId: '451148309163',
    projectId: 'taxiappdemo-1abe7',
    storageBucket: 'taxiappdemo-1abe7.firebasestorage.app',
    iosBundleId: 'com.example.taxiappdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPAqUP29ZGiugJMSqUkOADgtBkTfmc-W4',
    appId: '1:451148309163:web:7716d7f9d561c3d2e4cdee',
    messagingSenderId: '451148309163',
    projectId: 'taxiappdemo-1abe7',
    authDomain: 'taxiappdemo-1abe7.firebaseapp.com',
    storageBucket: 'taxiappdemo-1abe7.firebasestorage.app',
  );
}
